apiVersion: v1
kind: Secret
{{- with .Values.secrets }}
metadata:
  name: {{ .name }}
  labels:
    type: env-secret
data:
  ADMIN: {{ .data.adminPassword | b64enc }}
  PASSWORD: {{ .data.adminPassword | b64enc }}
{{- end }}